nx: 360
ny: 180

planet: earth
use_case: williamson_6
initially_geostrophic: False

enable_diffusion: True

cfl: 0.9
final_time: 1209600  # 14 days

print_interval: 43200  # 1 hour
output_directory: ../output/williamson-6
